
sudo: required

language: python
python:
    - "3.5"
    - "3.6"

services:
    - docker

before_install:
    - docker pull icepack/icepack:latest
    - docker run --interactive --tty --detach --volume $TRAVIS_BUILD_DIR:/repo --name build icepack/icepack:latest

install:
    - docker exec -i build bash -c ". /firedrake/bin/activate && cd /repo && python3 setup.py install"

script:
    - docker exec -i build bash -c ". /firedrake/bin/activate && cd /repo && MPLBACKEND='Agg' pytest --capture=no --verbose"

