version: 2.1

commands:
  build:
    steps:
      - checkout
      - run: pip install rasterio==1.3a4  # <- Dirty hack, remove later
      - run: pip install --editable ."[doc,opt]"
      - run: pip install pytest-cov codecov
  unittest:
    steps:
      - run: pytest --capture=no --verbose --cov=icepack
  realtest:
    steps:
      - run: cp ~/registry-nsidc.txt ~/icepack/icepack/
      - run: jupyter nbconvert --to notebook --execute notebooks/tutorials/03-larsen-ice-shelf.ipynb
  codecov:
    steps:
      - run: codecov
  styletest:
    steps:
      - run: pip install black>=22.0
      - run: black --check ./

jobs:
  python38:
    docker:
      - image: icepack/firedrake-python3.8:0.6.0
    working_directory: ~/icepack
    steps:
      - build
      - unittest
      - realtest
  python310:
    docker:
      - image: icepack/firedrake-python3.10:0.6.0
    working_directory: ~/icepack
    steps:
      - build
      - styletest
      - unittest
      - codecov
      - realtest

workflows:
  version: 2
  tests:
    jobs:
      - python38
      - python310
